export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const GET_CITIES_SUCCESS= "GET_CITIES_SUCCESS";
export const GET_CITIES_ERROR= "GET_CITIES_ERROR";
export const GET_BOOKING_DETAILS_SUCCESS= "GET_BOOKING_DETAILS_SUCCESS";
export const GET_BOOKING_DETAILS_ERROR= "GET_BOOKING_DETAILS_ERROR";


// export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
// export const LOG_IN_ERROR = "LOG_IN_ERROR";



export const GET_ROUTES_FAILURE = "GET_ROUTES_FAILURE";
